services:
  - postgresql

addons:
  postgresql: "9.5"

language: python
python:
 - "3.5"

sudo: required
before_install:
 - sudo apt-get update -qq
 - sudo -E apt-get -yq update &>> ~/apt-get-update.log
 - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
 - sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev libwebp-dev
 - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
 - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
 - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm
 - sudo apt-get install -qq libproj-dev gdal-bin python-gdal libgeoip1

install:
 - sudo apt-get install -y postgresql-9.5-postgis-2.3
 - echo "host all all 0.0.0.0/0 md5" | sudo tee -a /etc/postgresql/9.5/main/pg_hba.conf
 - echo "listen_addresses = '*'" | sudo tee -a /etc/postgresql/9.5/main/postgresql.conf
 - sudo service postgresql restart 9.5

env:
 - DJANGO_SETTINGS_MODULE=config.settings.test POSTGRES_USER=dc_traffic_tickets DJANGO_ADMIN_URL=testadmin DJANGO_ACCOUNT_ALLOW_REGISTRATION=True WAGTAIL_ADMIN_URL=wagtail_admin

install: "pip install -r requirements/test.txt"

before_script:
  before_script:
  - psql -c 'create database travis_postgis;' -U postgres

script: 'python manage.py test --settings=config.settings.test'
