sudo: true

services:
  - docker
  
before_install:
- docker-compose -f dev.yml build
- docker-compose -f dev.yml up -d 
- docker ps -a
- docker-compose -f dev.yml run django python manage.py test


language: python
python:
- "3.5"

