version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - redis
    command: /gunicorn.sh
    env_file: .env

  redis:
    image: redis:latest

  nginx-secure:
    build: ./compose/nginx-secure
    depends_on:
      - django
      - certbot

    ports:
      - "0.0.0.0:5000:80"

    environment:
      - MY_DOMAIN_NAME=dctraffictickets.net
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: quay.io/letsencrypt/letsencrypt
    # command: bash -c "sleep 6 && certbot certonly -n --standalone -d dctraffictickets.net -d www.dctraffictickets.net --text --agree-tos --email nathan.danielsen@gmail.com --server https://acme-staging.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --standalone-supported-challenges http-01"
    command: bash -c "sleep 6 && certbot certonly -n --standalone -d dctraffictickets.net -d www.dctraffictickets.net --text --agree-tos --email nathan.danielsen@gmail.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm
