# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 16:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('objectid', models.IntegerField()),
                ('rowid', models.IntegerField()),
                ('holiday', models.BooleanField()),
                ('violation_code', models.CharField(max_length=10)),
                ('violation_description', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('rp_plate_state', models.CharField(max_length=5)),
                ('body_style', models.CharField(max_length=5)),
                ('address_id', models.IntegerField()),
                ('streetsegid', models.FloatField()),
                ('xcoord', models.IntegerField()),
                ('ycoord', models.IntegerField()),
                ('filename', models.CharField(max_length=50)),
                ('ticket_issue_datetime', models.DateTimeField()),
            ],
        ),
    ]
