# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingviolation',
            options={'verbose_name_plural': 'Parking Violations'},
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='rowid',
            field=models.IntegerField(unique=True),
        ),
    ]
