# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160505_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingviolation',
            name='streetsegid',
            field=models.FloatField(),
        ),
    ]
