# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160817_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingviolation',
            name='body_style',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='rp_plate_state',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='ticket_issue_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='violation_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
