# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160823_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingviolation',
            name='rowid',
            field=models.IntegerField(),
        ),
    ]
