# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160905_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingViolationDataFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('imported', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Parking Violations Datasets',
            },
        ),
    ]
