# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_parkingviolationdatafiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingviolationdatafiles',
            options={'verbose_name_plural': 'Source Datasets - Parking Violations'},
        ),
    ]
