# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_parkingviolation_source_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingViolationFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=50)),
                ('fine', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Parking Violations Fines',
            },
        ),
    ]
