# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_parkingviolationfine'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingviolation',
            name='violation_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ParkingViolationFine'),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='filename',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='parkingviolationfine',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='parkingviolationfine',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolationfine',
            name='fine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolationfine',
            name='short_description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
