# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160923_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.IntegerField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Address IDs',
            },
        ),
        migrations.CreateModel(
            name='BodyStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_style', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Body Styles',
            },
        ),
        migrations.CreateModel(
            name='PlateState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_plate_state', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Reported Plate States',
            },
        ),
        migrations.CreateModel(
            name='StreetSegID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetsegid', models.FloatField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Street Segment IDs',
            },
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='filename',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkingviolation',
            name='address_id_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AddressID'),
        ),
        migrations.AddField(
            model_name='parkingviolation',
            name='body_style_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BodyStyle'),
        ),
        migrations.AddField(
            model_name='parkingviolation',
            name='rp_plate_state_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PlateState'),
        ),
        migrations.AddField(
            model_name='parkingviolation',
            name='streetsegid_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.StreetSegID'),
        ),
    ]
