# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160923_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressid',
            name='address_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodystyle',
            name='body_style',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='platestate',
            name='rp_plate_state',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='streetsegid',
            name='streetsegid',
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
