# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160923_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingviolation',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='address_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='objectid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='rowid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='violation_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='violation_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='xcoord',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='ycoord',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
