# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20160923_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingviolation',
            name='streetsegid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
