# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160923_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingviolationdatafiles',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolationdatafiles',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
