# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20160923_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingviolation',
            name='address_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='streetsegid',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingviolationdatafiles',
            name='filename',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
