# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20160923_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingviolation',
            name='address_id_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.AddressID'),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='body_style_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.BodyStyle'),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='rp_plate_state_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PlateState'),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='source_filename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ParkingViolationDataFiles'),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='streetsegid_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.StreetSegID'),
        ),
        migrations.AlterField(
            model_name='parkingviolation',
            name='violation_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ParkingViolationFine'),
        ),
    ]
