# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20161001_1430'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='parkingviolation',
            index_together=set([('id', 'ticket_issue_datetime')]),
        ),
    ]
