# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20161001_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingviolation',
            old_name='address_id_key',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='parkingviolation',
            old_name='body_style_key',
            new_name='body_style',
        ),
        migrations.RenameField(
            model_name='parkingviolation',
            old_name='source_filename',
            new_name='data_filename',
        ),
        migrations.RenameField(
            model_name='parkingviolation',
            old_name='rp_plate_state_key',
            new_name='rp_plate_state',
        ),
        migrations.RenameField(
            model_name='parkingviolation',
            old_name='streetsegid_key',
            new_name='streetsegid',
        ),
        migrations.RenameField(
            model_name='parkingviolation',
            old_name='violation_key',
            new_name='violation_code',
        ),
    ]
