# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_parkingviolationfine_compiled_ticket_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingviolationfine',
            old_name='code',
            new_name='violation_code',
        ),
    ]
