# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20161001_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingviolationfine',
            old_name='compiled_ticket_descriptions',
            new_name='json_data',
        ),
    ]
