# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20161001_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingviolationfine',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
