# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 01:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20161001_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressid',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='addressid',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
