# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20161004_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressid',
            name='address_num',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='address_suffix',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='advisory_neighborhood_commission',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='census_block',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='census_blockgroup',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='census_tract',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='neighbor_hood',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='neighbor_hood_cluster',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='official_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='police_district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='police_service_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='quadrant',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressid',
            name='resident_occupancy_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='residential_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='single_member_district',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='street_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='street_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='vote_precinct',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='ward',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addressid',
            name='zipcode',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
