# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20161004_0134'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='addressid',
            index_together=set([('id', 'address_id')]),
        ),
    ]
