# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20161004_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressid',
            name='advisory_neighborhood_commission',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='addressid',
            name='neighbor_hood_cluster',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='addressid',
            name='official_status',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressid',
            name='quadrant',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='addressid',
            name='single_member_district',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='addressid',
            name='vote_precinct',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='addressid',
            name='ward',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='addressid',
            name='zipcode',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
