# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20161004_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressid',
            name='census_block',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='addressid',
            name='census_blockgroup',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='addressid',
            name='census_tract',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
