# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20161004_2324'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='addressid',
            index_together=set([('census_tract', 'census_blockgroup', 'census_block'), ('id', 'address_id')]),
        ),
    ]
