# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0003_auto_20161028_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeformblogpage',
            name='author',
        ),
        migrations.AddField(
            model_name='freeformblogpage',
            name='intro',
            field=models.CharField(default='intro', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeformblogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
