# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 01:55
from __future__ import unicode_literals

import blog.blocks.markdown
import blog.blocks.restructured_text
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_freeformblogpagetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeformblogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('code_snippet', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('python', 'Python'), ('javascript', 'Javascript'), ('json', 'JSON'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('scss', 'SCSS'), ('yaml', 'YAML')])), ('code', wagtail.wagtailcore.blocks.TextBlock())))), ('restructured_text', blog.blocks.restructured_text.RSTBlock()), ('markdown', blog.blocks.markdown.MarkDownBlock()), ('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock())), blank=True),
        ),
    ]
