# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:09
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161028_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeformblogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.FreeFormBlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
