# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161028_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeformblogpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items_freeform', to='blog.FreeFormBlogPage'),
        ),
    ]
