# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_freeformblogpage_in_blog_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='in_blog_index',
            field=models.BooleanField(default=True, verbose_name='Include in Blog Index'),
        ),
    ]
